typography_spectrum: 0.26953120762482285
color:
  brandStrength: 0.5526046578306705
  lightness: 0.3988915232475847
  saturation: 0.9585263060871512
  rhythmicContrast: 0.06942577916197479
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.651646321406588
name: Android Call Recorder
navigation:
  - name: About
    url: about us
    type: external
title: Recorder 4 Android
description: Smart App for Calls Management
